<section id="terms_and_conditions">
	<h2>TERMS OF USE</h2>

	<h3>1.  ACCEPTANCE OF TERMS</h3>
	<p>Bunzy Inc. ("Bunzy"), provides Services (as defined below) to you through this website, including through any mobile application(s) connected with the website and Services, ("Website") and access to and use of the Website and the Services are provided to you subject to your acceptance of and compliance with the following terms and conditions ("Terms").</p>
	<p>By completing the registration process and indicating your acceptance to be bound by all of these Terms, you acknowledge that you have read, accepted, and agreed to these Terms. If you do not agree to these Terms, you will not be able to use the Website or the Services.</p>
	<p>In addition, when using the Services, you will be subject to any posted guidelines or rules applicable to such Services which may be posted from time to time. All such guidelines or rules are hereby incorporated by reference into these Terms. Bunzy reserves the right to change these Terms at any time without prior notice and your continued access or use of this Website or the Services after such changes indicates your acceptance of the Terms as modified. It is your responsibility to review these Terms regularly. These Terms were last updated on May 2, 2016.</p>
	<p>If you do not agree with one or more of these Terms, do not access or use this Website or the Services.</p>
	<h3>2.  REGISTRATION OBLIGATIONS</h3>
	<p>To use this Website, you must first complete the registration process to create an account ("Account") and select and register a unique user name and password (collectively, "Credentials"). Your Account and Credentials are specific to you and may not be shared with or transferred to any other person. You are solely responsible for maintaining the confidentiality of your Credentials and you will be held responsible for any harm caused by disclosing or resulting from any unauthorized use of your Credentials. You will not permit any other person to use your Account or Credentials, and you will immediately notify Bunzy if you know or suspect that your Account or Credentials have been used by any other person.</p>
	<p>During the registration process, you will provide true, accurate, current and complete information about yourself as prompted by the Service's registration form (such information being the "Registration Data"). You will also maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or complete, or Bunzy has reasonable grounds to suspect that such information is untrue, inaccurate, not current or complete, Bunzy has the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof) by you. Individuals under 18 years of age cannot register on any portion of this Website.</p>
	<p>Bunzy may act upon any communication that is given through your Account or by using your Credentials. Bunzy is not required to verify the actual identity or authority of a person using your Account or Credentials, but Bunzy may in its discretion at any time require verification of the identity of a person seeking to access your Account and may deny access to and use of your Account if Bunzy is not satisfied with the verification. If Bunzy, in its discretion, considers your Account or Credentials to be unsecure or to have been used inappropriately, then Bunzy may immediately cancel the Account or Credentials without any notice to you. You may be required to change your Credentials from time to time.</p>
	<h3>3.  DESCRIPTION OF SERVICES</h3>
	<p>Bunzy is offering to persons who have Accounts an internet driven platform to connect food enthusiasts with private cooks and commercial kitchens (the "Services"). The provision of the Services is subject to these Terms or other terms you accepted when making purchases or orders through the Website.</p>
	<h3>4.  PRIVACY POLICY</h3>
	<p>Your Credentials, Registration Data and any other information that you provide to us through this Website, as well as certain other information about you, is subject to Bunzy's Privacy Policy [insert link to Privacy Policy]. Your privacy is important to us. For more information, please see our Privacy Policy [insert link to Privacy Policy] for details.</p>
	<h3>5.  USE OF THE WEBSITE</h3>
	<p>Bunzy authorizes you to view content provided on this Website only in connection with your registering with Bunzy or using the Services. You may not remove any trade-mark, copyright or other proprietary notices from such copy nor modify the material or content in any way. Except as otherwise set out in these Terms, any copying or reproduction of this Website's materials or content, in whole or in part, for commercial purposes or distribution, re-transmission, republication, modification, reverse engineering, sale or other exploitation of this Website or this Website materials or content without the prior written permission of Bunzy is strictly prohibited. Bunzy reserves the right to take such steps as it deems necessary, including legal action, to restrain such unauthorized and prohibited activity and Bunzy reserves the right to suspend or terminate your access to any part of this Website or the Services immediately, without prior notice, at its sole discretion. You are solely and fully responsible for all consequences, however remote, resulting from your use of this Website or the Services.</p>
	<h3>6. YOUR INTERACTION WITH OTHER USERS</h3>
	<p>The Services anticipate three type of users (collectively referred to as “Users”, the first type being food consumers, whether not they have an Account (“Consumers”), the second being private cooks (“Cooks”) and the third type being commercial kitchens (“Kitchens”). Users may only use the Website and the Services in accordance with these Terms or other terms you accepted when posting User Content (defined below).</p>
	<p>Bunzy is not directly involved in any transaction between Consumers, Cooks and Private Kitchens. The Services facilitates interactions between Users who agree to comply with Bunzy's Terms, policies and the law.</p>
	<p>Bunzy is in no position to measure or control the quality, safety or value of items or services offered by any User on its Website. Bunzy does not warrant the truth or accuracy of any representation made with respect to any items or services, including whether Cooks and Kitchens are able to provide items or services stated.</p>
	<p>Bunzy assumes no responsibility to screen Users of the Website, other than as provided for elsewhere in these Terms. Bunzy cannot and will not ensure that any transaction facilitated by this Website and the Services will be completed.</p>
	<p>At no time does Bunzy take part in the transfer of ownership of items or services advertised and made available by Users on the Website or the Services.</p>
	<h3>7. FEES</h3>
	<p>There are no fees charged directly from Bunzy to Consumers for the use of the Services or access to the Website.</p>
	<p>Cooks and Kitchens are charged facilitation fees (“Fees”) in the event a Consumers place an order with Cooks or Kitchens through the Website. Fees charged by Bunzy are displayed on the Website and are subject to change at the sole discretion of Bunzy. Cooks and Kitchens must ensure that their final pricing listed on the Website takes Fees into account. Once the Consumers payment has been processed, the final amount, less Fees, for the goods/services offered by Cook and Kitchens will be deposited to the bank account indicated in the Registration Data. From time to time, Bunzy may offer free trials or other promotions (a "Promotion"). As an example, we may offer a Promotion that provides free access to the Services for Cooks and Kitchens for a certain period of time. COOKS AND KITCHENS WILL BE RESPONSIBLE FOR COLLECTING AND PAYING ANY APPLICABLE TAXES RELATING TO YOUR PAYMENTS AND WILL INDEMNIFY AND HOLD HARMLESS BUNZY FROM ANY AND ALL TAXES, INCLUDING SALES TAX, BASED ON ANY PAYMENTS MADE BY YOU IN CONNECTION WITH THE SERVICES.</p>
	<p>Bunzy bills Consumers through an online account (your "Billing Account") for use of the Services and for good/services which you have purchased. You agree to pay Bunzy all charges at the prices you agreed to for any use of the Services by you or other persons using your Billing Account, and you authorize Bunzy to charge your chosen payment provider (your "Payment Method") for transactions in which you enter via the Website and the Services. You agree to make payment using that selected Payment Method. Bunzy in its sole discretion may correct any billing errors or mistakes that it makes even if it has already requested or received payment.  The terms of the payments will be based on the Payment Method chosen and may be determined by agreements between Users and the financial institution, credit card issuer or other provider of your chosen Payment Method. If you initiate a chargeback or otherwise reverse a payment made with your Payment Method, Bunzy may in its discretion terminate your account immediately. If Bunzy successfully disputes the reversal, and the reversed funds are returned, you are not entitled to a refund or to have your Account reinstated. All payment information that you provide in connection with the Services must be accurate, current and complete. You represent and warrant that you have the legal right to use your Payment Method to pay any contribution.</p>
	<h3>8.  CANCELLATION</h3>
	<p>Where Cooks and Kitchens have accepted a request from a Consumer, Cooks and Kitchens agree to notify Bunzy and Consumers promptly if they become aware that they will be unable to provide the goods/services requested. No amounts will be charges to Consumers in relation to such cancellations, and failure to comply with this provision may lead to termination of the account and use of the Services by Cooks and Kitchens.</p>
	<p>Should Consumers wish to cancel orders made from Cooks and Kitchens, they must do so promptly after such order has been placed. Orders not cancelled within 15 minutes of placement shall be deemed valid and not subject to a refund.</p>
	<h3>9.  TRADE-MARKS AND COPYRIGHT</h3>
	<p>Bunzy Inc., this Website domain and other trade names or trade-marks of Bunzy used on this Website, and related words and logos are trade-marks or trade-names of Bunzy in Canada and other jurisdictions. Nothing in these Terms or on this Website will be construed as granting or conferring, either expressly, by implication, by estoppel or otherwise, a licence or other right to you to use any such marks or names or any other intellectual property right of Bunzy. The names of other companies, products and services referred to on this Website may be trade-marks or trade-names of their respective owners. Any unauthorized use of the trade-marks or trade-names of Bunzy or of third parties is strictly prohibited.</p>
	<p>The materials provided on this Website including, without limitation, all portions of this Website, content, site design, text, graphics and the selection and arrangement thereof, are protected by copyright. All rights reserved. Title to the Bunzy materials remains with Bunzy and any unauthorized use of such materials is strictly prohibited. Bunzy reserves the right to take such steps as it deems necessary, including legal action, to enforce its rights under trade-mark and copyright law.</p>
	<h3>10.  USER GENERATED CONTENT</h3>
	<p>Portions of this Website allow Users to post and exchange information, ideas and opinions ("User Content"), but Bunzy does not screen, edit or review any User Content before they are posted or transmitted. Please note that User Content do not necessarily reflect the views of Bunzy, and Bunzy disclaims all responsibility for any such User Content and for any losses or expenses resulting from their use or appearance on this Website. You may not post on the Website or as part of the Services, or transmit to Bunzy or any other user (either on or off the Website), any offensive, inaccurate, abusive, obscene, profane, sexually oriented, threatening, intimidating, harassing, racially offensive, or illegal material, or any material that infringes or violates another person’s rights (including intellectual property rights, and rights of privacy and publicity).</p>
	<p>We value your visit to this Website and welcome any questions, comments or feedback you might have about this Website, these Terms or any of the products or services offered by Bunzy ("Feedback"). Please refer to the Contact section of this Website for phone and fax numbers and email addresses.</p>
	<p>By posting User Content or Feedback on the Website or as part of the Services, you automatically grant to Bunzy, its affiliates, licensees and successors, an irrevocable, perpetual, non-exclusive, fully paid-up, worldwide right and licence to (i) use, copy, store, perform, display, reproduce, record, play, adapt, modify and distribute the User Content or Feedback, (ii) prepare derivative works of the User Content or Feedback or incorporate the User Content or Feedback into other works, and (iii) grant and authorize sublicenses of the foregoing in any media now known or hereafter created. You represent and warrant that any posting and use of your User Content or Feedback by Bunzy will not infringe or violate the rights of any third party.</p>
	<p>Bunzy cannot and does not guarantee the identity, age or location of any user. For that reason, Bunzy recommends that users communicate directly using the tools provided by the Website. All users agree to exercise caution and good judgment in making use of the Services and the Website.</p>
	<p>Prior to posting to the Website, Cooks and Kitchens hereby acknowledge, represent and warrant:</p>
	<ol style="list-style-type: lower-alpha">
		<li>that all information submitted or posted to the Website are true and accurate;</li>
		<li>that all prices, quantities, locations and times specified can be strictly adhered to;</li>
		<li>that there is strict compliance with all applicable industry standards and local laws, including the obligation to obtain any and all permits required by the laws of the jurisdiction;</li>
		<li>that all necessary precautions shall be taken to protect the safety of Consumers and the privacy of Consumer information in accordance with the Bunzy Privacy Policy;</li>
		<li>not to accept any additional gratuity or require any other payments above and beyond those you have expressly listed on the Website; and</li>
		<li>not to solicit Consumers in an effort to circumvent any fees that are paid or would be payable to Bunzy through the use of the Services.</li>
	</ol>
	<h3>11.  LINKS/CONNECTIONS TO OTHER SITES</h3>
	<p>Hyperlinks on this Website are provided for your convenience only. These links do not imply an endorsement of any linked sites or an affiliation with their owners or operators. Bunzy has no control over the content of any linked site. This content is the sole responsibility of the owner or operator of the linked site.</p>
	<p>The Services may allow Users to connect with various social networking sites (e.g. Facebook). By connecting your social networking sites account, you represent that you are entitled to grant us access to your social networking site account without breach by you of any social networking site terms and conditions and without obligating us to pay any fees or making us subject to any usage limitations. By granting Bunzy access to your social networking site account, you understand that we may access, make available, and store any information, content, or other materials that you have provided to or stored in your social networking site account ("SNS Content") accessible through the Website and Services so that it is available on your Account. Unless otherwise specified in these Terms, all SNS Content will be deemed to form part of User Content. Please note that your relationship with each social networking site is governed solely by your agreement(s) with such social networking site. Bunzy makes no effort to review any SNS Content for any purpose, including but not limited to, for accuracy, legality or non-infringement, and Bunzy is not responsible for any SNS Content.</p>
	<h3>12.  ACCEPTABLE USE AND RESTRICTIONS</h3>
	<p>In addition to complying with these Terms, you agree to use this Website, the Services and materials on this Website for lawful purposes only and in a manner consistent with local, national or international laws and regulations. Some jurisdictions may have restrictions on the use of the Internet by their residents.</p>
	<p>Potential users of this Website or the Services, in any jurisdiction of the world whose laws would: (i) void these Terms in whole or in any essential part (the essential parts being at least, but not only, the provisions relating to governing law, and limitation of liability); or (ii) render accessing this Website illegal; are unauthorized to use this Website.</p>
	<p>You agree not to use the Services or this Website in any manner that: (i) infringes, violates or misappropriates the intellectual property rights of any third party; or (ii) may be considered defamatory, discriminatory or otherwise malicious or harmful to any person or entity.</p>
	<h3>13.  INDEMNITY</h3>
	<p>Users will defend, indemnify and hold harmless Bunzy from and against any and all losses, damages, costs, expenses (including legal fees), claims, complaints, demands, actions, suits, proceedings, obligations and liabilities (including settlement payments) arising from, connected with or relating to your use of this Website, its content or materials, or the Services, including by the purchase and consumption of foods and food-related products, User Content or Feedback, or your negligence, misconduct, or breach of these Terms. Notwithstanding the foregoing, Bunzy retains the right to participate in the defense of and settlement negotiations relating to any third party claim, complaint, demand, action, suit or proceeding with counsel of its own selection at its cost and expense.</p>
	<p>For greater certainty, everyone who offers food or other goods and services for sale through the Website represents and warrants to Bunzy that it is and will remain at all times in compliance with all laws, including federal and provincial legislation, regulations made pursuant to such legislation, municipal by-laws and regulations and the common law of the jurisdiction, applicable to it in the jurisdiction in which it resides in respect of, among other things, the production and labelling of its products and all relevant health and safety considerations and hereby indemnifies Bunzy of same in the event of any breaches of the warranty provided herein.</p>
	<p>In no event shall Bunzy be liable under contract, tort, strict liability, negligence or other legal theory with respect to the Website, the Services or any User Content (i) for any lost profits or special, indirect, incidental, punitive, or consequential damages of any kind whatsoever, (ii) to provide substitute goods or services (however arising), or (iii) for any direct damages in excess of (in the aggregate) one hundred Canadian dollars (CDN$100).</p>
	<h3>14.  DISCLAIMERS</h3>
	<p>You understand and agree that:</p>
	<ol style="list-style-type: lower-alpha">
		<li>Use of this Website and the Services is at your sole risk. This Website and the Services are provided on an "as is", "as available" basis. Neither Bunzy, its parent, subsidiaries, affiliates, nor any of their respective employees, agents, officers, directors or third party service providers (collectively, "Bunzy Parties") make any warranty or condition of any kind, whether express or implied, regarding this Website, the Services or any items or services offered by Cooks and Kitchens and Bunzy Parties specifically disclaim the implied warranties and conditions of merchantable quality, fitness for a particular purpose and non-infringement of third party rights, to the maximum extent permitted by law.</li>
		<li>Bunzy Parties make no warranties or conditions regarding the quality, reliability, timeliness or security of the Services or that the Services will be uninterrupted or error-free. Bunzy Parties assume no responsibility or liability for the deletion or failure to store or access, or to store or access properly, email messages and electronic files. You assume the entire risk in downloading or otherwise accessing any data, files or other materials obtained from third parties as part of the Services, even if you have paid for virus protection services.</li>
		<li>The access to and downloading of material from this Website is done at your own risk. Bunzy makes reasonable efforts to ensure that this Website is virus-free, but Bunzy does not at any time guarantee or warrant that such materials are free of viruses, worms, Trojan horses or other destructive code. You are responsible for implementing safeguards to protect your computer system and data and you are responsible for the entire cost of any service, repairs or corrections necessary as a result of the use of this Website or the Services.</li>
	</ol>
	<h3>15.  LIMITATIONS OF LIABILITY</h3>
	<p>In no event will bunzy be liable to you for any direct, indirect, consequential, incidental, special, compensatory or punitive damages or losses or damages for loss of income, loss of business profits, business interruption, loss of data or business information, loss of or damage to property and claims of third parties or other pecuniary loss, INCLUDING PERSONAL INJURY OR DEATH, arising out of or related to these terms, the use of this website or the services. Bunzy parties will not be liable for any actual or alleged infringement by any third party materials available through the services. In no event will the cumulative liability of company parties arising out of or related to these terms exceed the amount of one hundred Canadian dollars (Cdn$100.00). To the extent that some jurisdictions do not allow exclusions or limitations on some categories of damages, these exclusions or limitations may not apply to you.</p>
	<p>The foregoing disclaimers and limitations of liability apply regardless of the causes, circumstances or form of action giving rise to the loss, damage, claim or liability, even if such loss, damage, claim or liability is based upon breach of contract (including, without limitation, a claim of fundamental breach or breach of a fundamental term), tort (including, without limitation, negligence), strict liability or any other legal or equitable theory, and even if advised of the possibility of the loss, damage, delay, claim or liability.</p>
	<p>You acknowledge and agree that these Terms present a fair allocation of risk and liability, and that this Section 15 is an essential part of the bargain between the parties, a controlling factor in setting any fees or other charges, and an inducement to the parties to enter into these Terms.</p>
	<h3>16.  GENERAL</h3>
	<p>These Terms, the Privacy Policy and all other notices, policies and statements contained on this Website (all as may be amended by Bunzy from time to time without prior notice) constitute the entire agreement between Bunzy and you. These Terms cannot be modified except as described herein. Anything in this Website inconsistent with these Terms is superseded by these Terms. No waiver of any of these Terms will be deemed a further or continuing waiver of such Term or any other Term. If in any jurisdiction, any of these Terms are held to be unenforceable by a court of competent jurisdiction, such Terms will be restricted or eliminated to the minimum extent necessary and the remaining Terms will otherwise remain in full force and effect. The headings used in these Terms are included for convenience only and will not limit or otherwise affect these Terms.</p>
	<p>These Terms and the subject matter of these Terms and all related matters will be governed by, and construed in accordance with, the laws of the Province of Ontario, Canada and the laws of Canada applicable in Ontario, excluding any laws that implement the United Nations Convention on Contracts for the International Sale of Goods or the United States Uniform Commercial Code, and excluding any rules of private international law or the conflict of laws that would lead to the application of any other laws. Subject to the following paragraph, you submit to the exclusive jurisdiction of the courts of the Province of Ontario.</p>
	<p>Nothing contained in these Terms or the use of the Website and Services by any User, whether Cooks, Kitchens, Consumers or otherwise, shall be construed to create or imply a joint venture, partnership, principal-agent, or employment relationship with Bunzy. Bunzy’s responsibilities are strictly limited to the Services.</p>
	<p>Users agree to work in good faith to resolve disputes that may arise out of or relating to the Services, this Website, these Terms or the Privacy Policy. If such negotiations do not resolve the dispute to the satisfaction of both parties then Bunzy will refer the matter to a mutually agreed upon mediator, who will meet with the parties to the dispute and attempt to reach a mutually agreeable binding resolution of the dispute. Such mediation will be performed pursuant to the National Mediation Rules of the ADR Institute of Canada, Inc. The place of mediation shall be Toronto, Ontario, Canada. The language of the mediation shall be English. If mediation does not resolve the dispute to the satisfaction of both parties then, to the extent permitted by applicable law, unless Bunzy agrees otherwise, any claim, dispute or controversy, whether in contract or tort, pursuant to statute or regulation, or otherwise, and whether pre-existing, present or future, arising out of or relating to the Services, this Website, these Terms or the Privacy Policy, will be determined by final and binding arbitration to the exclusion of the courts. The arbitration will be conducted in the province of Ontario, on a simplified and expedited basis by one arbitrator pursuant to the current laws and rules relating to commercial arbitration in the Ontario on the date of the notice. The foregoing does not, however, preclude Bunzy from seeking injunctive relief in other jurisdictions when necessary to protect its interests. You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated or representative action. If for any reason a claim proceeds in court rather than in arbitration, you waive any right to a jury trial.</p>
	<p>YOU AGREE THAT IF YOU ARE DISSATISFIED WITH THE WEBSITE OR ANY SERVICES OFFERED IN CONNECTION WITH THE WEBSITE, IF YOU DO NOT AGREE WITH ANY PART OF THESE TERMS, OR IF YOU HAVE ANY OTHER DISPUTE OR CLAIM WITH OR AGAINST BUNZY CONCERNING YOUR USE OF THE WEBSITE OR ACCESS TO THE SERVICES OR OTHERWISE TO DO WITH THESE TERMS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE WEBSITE AND ANY SERVICES OFFERED IN CONNECTION WITH THE WEBSITE.</p>
	<h3>17.  CONTACT US</h3>
	<p>We value your visit to this Website and welcome any questions or comments you might have about this Website, these Terms, or any of the products or services offered by Bunzy. Please refer to the Contact section of this Website for phone, email addresses and other ways to contact us.</p>
</section>